### ISSUE TITLE
db failed to initialize when db persistence is enabled

### ISSUE THREAD

**Issue by attiasr** [supabase-community/supabase-kubernetes#57]
# Bug report

## Describe the bug

when enabling persistence on db, the db failed to start with the following error:
```
initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
initdb: detail: It contains a lost+found directory, perhaps due to it being a mount point.
initdb: hint: Using a mount point directly as the data directory is not recommended.

```
## To Reproduce
edit the values.examples.yaml and change the db persistence to true and install the helm chart:
```
db:
  enabled: true
  image:
    tag: 15.1.0.147
  livenessProbe:
    exec:
      command:
        - pg_isready
        - -U
        - postgres
    initialDelaySeconds: 3
  persistence:
    enabled: true
    size: 2Gi
```

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

I expect a successful installation and initiation of all pods in the cluster
## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]
