### ISSUE TITLE
No dashboard gateway authentication

### ISSUE THREAD

**Issue by Velka-DEV** [supabase-community/supabase-kubernetes#70]
# Bug report

## Describe the bug

When browsing to my studio url, there is no "auth" page that protect the studio like it should be (i guess ?).

I foud this issue about the same problem (#33) but it ended with nothing while the self-hosting docker [doc clearly make mention off that mechanism](https://supabase.com/docs/guides/self-hosting/docker#dashboard-authentication)

And the values are declared so should be used:

```yaml
  dashboard:
    username: ****
    password: *****
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Clean fresh deploy using values for dashboard auth.

## Expected behavior

The dashboard should be protected with credentials.

## System information

- OS: any (macOS 18)
- Browser (if applies) any (arc)

```yaml
studio:
  image:
    tag: 20240326-5e5586d
    
kong:
  image:
    repository: kong
    tag: 2.8.1
```
