### ISSUE TITLE
cannot set up supabase self host. Almost every deployment does not start

### ISSUE THREAD

**Issue by lb-ovc** [supabase-community/supabase-kubernetes#78]
# Bug report
Nothing works. 

## Describe the bug

I am trying to setup selfhost since around 8 hours now. Tried everything and nothing works.

This is how it currently looks:
![image](https://github.com/user-attachments/assets/ef952d28-f2e2-4b84-8400-4e9b3f767781)

## To Reproduce

Clone and edit the values.yaml following exactly the "Customize" section of the documentation. 

Config i did: 

``` 
SMTP_ADMIN_MAIL = "blabla@blabla.de"
SMTP_HOST="strato"
SMTP_PORT="463"
SMTP_SENDER_NAME="blabla"
```

Generated the jwt secrets like told
```
secret:
  jwt:
    anonKey: eyJhbGci...3ZO2g
    serviceKey:eyJhbGciOi...NA10c5A
    secret: 4RgG4u...Q==
```

set the smpt secret like told:
```
secret:
  smtp:
    username: blabla@blabla.de
    password: secretpasswordcensored
```

set the db secret:
```
secret:
  db:
    username: supabase
    password: supersecretpasswordcensored
    database: supabase
   host: 10.....0 # added this line to point to my external database running on a hetzner server (installing this on master which can access the local ip address of the db server) 
   port: 5432 # added this also
   # specify existing secret, which takes precedence over variables above
   secretRef: ""
    # override secret keys for existing secret refs
   secretRefKey:
     username: username
     password: password
     database: database
     host: host
     port: port
```

disabled the db image because i have the external database
```
db:
   enabled: false
```

Updated the dashboard secret
```
secrets:
  dashboard:
    username: myusername
    password: supersecurecensoredpassword
    # specify existing secret, which takes precedence over variables above
    # secretRef: ""
    # override secret keys for existing secret refs
    secretRefKey:
      username: username
      password: password
```

generated a key with the `openssl rand 64 | base64` command for the analytics key
```
 analytics:
    apiKey: "8Zzj+...UhiQ=="
    # specify existing secret, which takes precedence over variable above
    # override secret keys for existing secret refs
    secretRefKey:
      apiKey: apiKey
```

we are using exoscale for the s3 so i did this config:
```
secrets:
  s3:
    keyId: "xyz"
    accessKey: "LW...zq0"
    # specify existing secret, which takes precedence over variables above
    # secretRef: ""
    # override secret keys for existing secret refs
    secretRefKey:
      keyId: keyId
      accessKey: accessKey
```

and 

```
storage: 
environment:
    # Override the database hostname if using external database
    DB_HOST: 10.xxxxx.5
    DB_USER: supabase_storage_admin # does this need to be changed to my supabase user from my external db??
    DB_PORT: 5432
    DB_DRIVER: postgres
    DB_SSL: disable  # disable, allow, prefer, require, verify-ca, verify-full
    PGOPTIONS: -c search_path=storage,public
    FILE_SIZE_LIMIT: "52428800"
    STORAGE_BACKEND: file  # file, s3
    FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    TENANT_ID: stub
    REGION: stub
    GLOBAL_S3_BUCKET: app
    # Set variables below and secret.s3 above to enable S3 storage bucket
    # If using this chart's minio, skip the endpoint and protocol below
    STORAGE_BACKEND: s3
    GLOBAL_S3_ENDPOINT: https://sos-de-fra-1.exo.io
    GLOBAL_S3_PROTOCOL: https
    GLOBAL_S3_FORCE_PATH_STYLE: true

```

the last thing was setting every example.com in the value.yaml to `https://supabase.mywebsite.de` and for the kong config the host to `supabase.mywebsite.de`

Copied the config to my server and ran `helm install bfh -f config.yaml .`

Output:

```
root@master-1:~/supabase-kubernetes/charts/supabase# helm install bfh -f config.yaml .
walk.go:74: found symbolic link in path: /root/supabase-kubernetes/charts/supabase/ci/example-values.yaml resolves to /root/supabase-kubernetes/charts/supabase/values.example.yaml. Contents of linked file included and used
W0728 21:27:57.968324  795993 warnings.go:70] spec.template.spec.containers[0].env[35].name: duplicate name "GOTRUE_SMTP_PASS"
NAME: bfh
LAST DEPLOYED: Sun Jul 28 21:27:52 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
---
Thank you for installing supabase!

Visit the Studio dashboard at http://supabase.mywebsite.de

```

initDB returns "accepting Connections"

## Expected behavior

Services and pods to start without an error.

## Screenshots

So here is the log from every failed deployments:

analytics:
[bfh-supabase-analytics-6c8ffcd7cc-2s42t_supabase-analytics.log](https://github.com/user-attachments/files/16405313/bfh-supabase-analytics-6c8ffcd7cc-2s42t_supabase-analytics.log)

auth: 
Cant even download the logs
![image](https://github.com/user-attachments/assets/19d50f59-0183-4651-9fdc-dfd57af63a29)

functions:
![image](https://github.com/user-attachments/assets/2a95062a-980c-4253-905b-1855c61c022a)

meta:
![image](https://github.com/user-attachments/assets/8ebfa70d-0408-4b38-9b57-e3ce652f86e6)

realtime:
[bfh-supabase-realtime-5dd674d7d5-whlbh_supabase-realtime.log](https://github.com/user-attachments/files/16405317/bfh-supabase-realtime-5dd674d7d5-whlbh_supabase-realtime.log)

rest:
[bfh-supabase-rest-6fdf6ccd44-wmbwn_supabase-rest.log](https://github.com/user-attachments/files/16405319/bfh-supabase-rest-6fdf6ccd44-wmbwn_supabase-rest.log)

storage:
[bfh-supabase-storage-6574cf9844-7zwpv_supabase-storage.log](https://github.com/user-attachments/files/16405322/bfh-supabase-storage-6574cf9844-7zwpv_supabase-storage.log)

vector:
![image](https://github.com/user-attachments/assets/f2e45537-ba7f-433e-89fd-6c3711fe0bf4)

## Additional context

This is just really frustrating having a so bad documented documentation for such a cool product like supabase...
