### ISSUE TITLE
Starter Example Setup Not Working

### ISSUE THREAD

**Issue by michaelGradial** [supabase-community/supabase-kubernetes#98]
# Bug report

## Describe the bug

When trying to do the most basic setup of this helm chart, I am unable to get things running on minikube. All the pods startup. But even after I try to enable minikube ingress addon, and make the updates to my /etc/host. But, the connection can't be made when I try to route to it, and it forever loads.

Even when trying to directly port forward to the supabase studio, when I navigate via port forward localhost, the port forward connection is immediately terminated
```
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000
Handling connection for 3000
Handling connection for 3000
E1214 09:51:59.250911   39542 portforward.go:413] an error occurred forwarding 3000 -> 3000: error forwarding port 3000 to pod 5987f914400dd6e8fa58388c15921d2eae0a1df2305f82f1d4aa2a031c242267, uid : exit status 1: 2024/12/14 17:51:59 socat[14291] E connect(5, AF=2 127.0.0.1:3000, 16): Connection refused
error: lost connection to pod
```

When trying to ping the minikube ip, the requets timeout

## To Reproduce

Following the basic clone and helm deploy command from the repository on a brand new minikube setup.

## Expected behavior

Hello world level application should start up.

## System information

- OS: macOs

**Comment by MarkE16** [comment]
Also experiencing this issue on Windows.

**Comment by TripShade** [comment]
Try mine. As soon as I get it completely fixed, I'll create a pull to fix main. My values.yaml assumes RWX volumes are possible; its using a storage class created by OpenEBS. I recommend creating a separate Postgres deployment Bitnami/Postgres always works for me. Paste the postgres secrets in the values.yaml and change the YOUR-DOMAIN placeholders. Its possible you have to create DB schemas _realtime, auth, storage, graphql_public. Its far from perfect but it works. Use https://supabase.com/docs/guides/self-hosting/docker#generate-api-keys to generate keys for jwt.

```yaml
secret:
  jwt:
    anonKey: jwt
    serviceKey: jwt
    secret: jwt-secret
  smtp:
    username: your-mail@example.com
    password: example123456
  dashboard:
    username: supabase
    password: SomePWDYouChoose
  db:
    username: postgres
    password: SomePWDYouGetFromBitnamiPostgres
    database: postgres
    # override secret keys for existing secret refs
    secretRefKey:
      username: username
      password: password
      database: database
  analytics:
    apiKey: your-super-secret-and-long-logflare-key

db:
  enabled: false

studio:
  image:
    tag: latest
  environment:
    STUDIO_DEFAULT_ORGANIZATION: "My Organization"
    STUDIO_DEFAULT_PROJECT: "My Project"
    SUPABASE_PUBLIC_URL: https://YOUR-DOMAIN/
    NEXT_PUBLIC_ENABLE_LOGS: "true"
  livenessProbe:
    httpGet:
      path: /api/profile
      port: 3000
    initialDelaySeconds: 3
  autoscaling:
    enabled: false

auth:
  enabled: true
  image:
    tag: v2.167.0
  environment:
    DB_HOST: postgres-supabase-postgresql
    DB_USER: postgres
    DB_AFTER_CONNECT_QUERY: "SET search_path TO public"
    API_EXTERNAL_URL: https://YOUR-DOMAIN
    GOTRUE_SITE_URL: https://YOUR-DOMAIN
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "false"
    GOTRUE_MAILER_AUTOCONFIRM: "true"
    GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@example.com"
    GOTRUE_SMTP_HOST: "smtp.example.com"
    GOTRUE_SMTP_PORT: "587"
    GOTRUE_SMTP_SENDER_NAME: "your-mail@example.com"
  autoscaling:
    enabled: false

rest:
  image:
    tag: latest
  autoscaling:
    enabled: false
  environment:
    DB_HOST: postgres-supabase-postgresql
    DB_USER: postgres

realtime:
  enabled: true
  image:
    tag: latest
  environment:
    APP_NAME: "Realtime"
    DB_HOST: postgres-supabase-postgresql
    DB_USER: postgres
    DB_AFTER_CONNECT_QUERY: "SET search_path TO _realtime"
  livenessProbe:
    httpGet:
      path: /
      port: 4000
    initialDelaySeconds: 3
  autoscaling:
    enabled: false

meta:
  enabled: true
  image:
    tag: v0.85.0
  environment:
    DB_HOST: postgres-supabase-postgresql
    DB_USER: postgres
  autoscaling:
    enabled: false

storage:
  enabled: true
  image:
    tag: latest
  environment:
    LOG_LEVEL: debug
    DB_HOST: postgres-supabase-postgresql
    DB_USER: postgres
    DB_INSTALL_ROLES: true
    PGOPTIONS: -c search_path=storage,public
  livenessProbe:
    httpGet:
      path: /status
      port: 5000
    initialDelaySeconds: 3
  persistence:
    enabled: true
    storageClassName: nfs-rwx-storage
    accessMode: ReadWriteMany
  autoscaling:
    enabled: false

imgproxy:
  enabled: false
  image:
    tag: latest
  environment:
    IMGPROXY_ENABLE_WEBP_DETECTION: "true"
  livenessProbe:
    exec:
      command:
        - imgproxy
        - health
    initialDelaySeconds: 3
  persistence:
    enabled: true
  autoscaling:
    enabled: false

kong:
  enabled: true
  image:
    repository: kong
    tag: latest
  environment:
    KONG_LOG_LEVEL: debug
  autoscaling:
    enabled: false
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/rewrite-target: /
    tls:
      - secretName: supabase-ingress-tls
        hosts:
          - YOUR-DOMAIN
    hosts:
      - host: YOUR-DOMAIN
        paths:
          - path: /
            pathType: Prefix

analytics:
  enabled: false
  image:
    tag: latest
  livenessProbe:
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 3

vector:
  enabled: false
  image:
    tag: latest-alpine
  autoscaling:
    enabled: false
  livenessProbe:
    httpGet:
      path: /health
      port: 9001
    initialDelaySeconds: 3
  ## Vector requires logs from the control plane to function.
  ## This is normally stored in /var/log/pods
  ## Modify these values according to your environment.
  volumeMounts:
    - name: pod-logs
      mountPath: /var/log/pods
  volumes:
    - name: pod-logs
      hostPath:
        path: /var/log/pods

functions:
  enabled: false
  image:
    tag: latest
  autoscaling:
    enabled: false

```
